import React from "react"
import "./portfolio.css"
import intercity from "../../assets/intercity.png"
import Aichecker from "../../assets/aichecker.png"
import howbodi from "../../assets/howbodi.png"
import fixmeet from "../../assets/fixmeet.png"
import jojolo from "../../assets/jojolo.png"
import myestate from "../../assets/myestate.png"

const Portfolio = () => {
  return (
    <section id="portfolio">
      <h5>My recent Works</h5>
      <h2>Portfolio</h2>
      <div className="container portfolio_container">
        <article className="portfolio_item">
          <div className="portfolio_item-image">
            <img src={intercity} alt="intercity page" />
          </div>
          <h3>Intercity Web Site</h3>
          <div className="portfolio_item-cta">
            {" "}
            <a
              href="http://github.com"
              target="_blank"
              rel="noreferrer"
              className="btn"
            >
              Github
            </a>
            <a
              href="http://intercity.ng"
              target="_blank"
              rel="noreferrer"
              className="btn btn-primary"
            >
              Demo
            </a>
          </div>
        </article>
        <article className="portfolio_item">
          <div className="portfolio_item-image">
            <img src={Aichecker} alt="fizee foods" />
          </div>
          <h3>Free AI Content Detector Tool, to Identify when texts are generated by AI(GPT-3, GPT-4, BARD, OpenAI, and Other AI Tools)</h3>
          <div className="portfolio_item-cta">
            {" "}
            <a
              href="https://github.com/Ifizeesneh/"
              target="_blank"
              rel="noreferrer"
              className="btn"
            >
              Github
            </a>
            <a
              href="https://aicheckertool.com/"
              target="_blank"
              rel="noreferrer"
              className="btn btn-primary"
            >
              Demo
            </a>
          </div>
        </article>
        <article className="portfolio_item">
          <div className="portfolio_item-image">
            <img src={howbodi} alt="howbodi page" />
          </div>
          <h3>Howbodi Website</h3>
          <div className="portfolio_item-cta">
            {" "}
            <a
              href="http://github.com"
              target="_blank"
              rel="noreferrer"
              className="btn"
            >
              Github
            </a>
            <a
              href="https://howbodi.io"
              target="_blank"
              rel="noreferrer"
              className="btn btn-primary"
            >
              Demo
            </a>
          </div>
        </article>
        <article className="portfolio_item">
          <div className="portfolio_item-image">
            <img src={fixmeet} alt="Fixmeet App" />
          </div>
          <h3>Fixmeet App for sheduled meetings</h3>
          <div className="portfolio_item-cta">
            {" "}
            <a
              href="https://github.com/Ifizeesneh/"
              target="_blank"
              rel="noreferrer"
              className="btn"
            >
              Github
            </a>
            <a
              href="https://fixmeet.app/"
              target="_blank"
              rel="noreferrer"
              className="btn btn-primary"
            >
              Demo
            </a>
          </div>
        </article>
        <article className="portfolio_item">
          <div className="portfolio_item-image">
            <img src={jojolo} alt="intercity page" />
          </div>
          <h3>Jojolo App to speak or chat with a doctor or childcare specialist</h3>
          <div className="portfolio_item-cta">
            {" "}
            <a
              href="https://github.com/Ifizeesneh/"
              target="_blank"
              rel="noreferrer"
              className="btn"
            >
              Github
            </a>
            <a
              href="https://www.jojoloapp.com/"
              target="_blank"
              rel="noreferrer"
              className="btn btn-primary"
            >
              Demo
            </a>
          </div>
        </article>
        <article className="portfolio_item">
          <div className="portfolio_item-image">
            <img src={myestate} alt="My Estate App" />
          </div>
          <h3>My Estate App</h3>
          <div className="portfolio_item-cta">
            {" "}
            <a
              href="https://github.com/Ifizeesneh/"
              target="_blank"
              rel="noreferrer"
              className="btn"
            >
              Github
            </a>
            <a
              href="https://myestate.app/"
              target="_blank"
              rel="noreferrer"
              className="btn btn-primary"
            >
              Demo
            </a>
          </div>
        </article>
      </div>
    </section>
  )
}

export default Portfolio
